### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by bengfarrell** [halvves/shader-doodle#1]
Hey! I had a similar idea awhile back, but I didn't follow through with anything after making it. I dig that you're tying into Shader Toy. You list next steps as webcam support. That's like the main thing mine supports. I also created a simple tooling task to turn glsl files into ES6 modules.

Anyway I wouldn't mind seeing something come out of my efforts, and you're doing something so similar...

Here's mine: https://github.com/creativecode-webcomponents/ccwc-video

If you want to do it all yourself, I completely understand - but I could see if it's easy to port my code if you're interested (or the other way around, whatever).

**Comment by mmmerl** [comment]
Hey! I am always open to collaboration. Looks like a cool project.

I would love help in determining a very usable/accessible api that is also modular/powerful. Maybe take a look at #2 and see if you have any thoughts there. I've run into a few limitations with the simplicity of the current api. Before I ran into these problems, I was hoping that texture/video would be a simple attribute on `<shader-doodle />` like `<shader-doodle texture="url" />`, but now I'm leaning a more component based, modular api. One thought for videos/textures I had, would be to have another custom component that would be used as a child of `<shader-doodle />`

like:

```
<shader-doodle>
  <shader-doodle-texture src="video/url.mp4" type="..." name="u_video_texture" />
</shader-doodle>
```

**Comment by bengfarrell** [comment]
Interesting - I like how you're thinking. Mine too has a src attribute, but having children that maybe you could reference as textures/uniforms would be so expandable. Perhaps src could autocreate a child if it doesn't exist and would be easier to approach for simple cases. Anyway, I think I'm relatively free this weekend, I'm hoping to clone/fork this and look things over. thanks!

**Comment by mmmerl** [comment]
Going to close this issue now that the collab ball is rolling and some of the initial webcam/texture/modular components have been fleshed out.
