### ISSUE TITLE
[BUG] sd-texture: external image in `src` and `force-update` leads to a WebGL error

### ISSUE THREAD

**Issue by abeluzhenko** [halvves/shader-doodle#28]
**Describe the bug**
`sd-texture` with an external image url as a source and `force-update` attribute produces a WebGL `INVALID_VALUE` error.

**To Reproduce**
1. Use an external url for the `src` attribute of an `sd-texture` element. 
2. Add a `force-update` attribute to the element.
3. Clear the browser's cache and use network throttling to be sure the image loads after the component was instantiated.
4. When the image is loaded, it doesn't set as a texture, a `WebGL: INVALID_VALUE: texImage2D: no canvas` error in the console.

**Expected behavior**
An image is set a as texture when loaded, no WebGL errors in the console.

**Screenshots**
http://s.csssr.ru/UGLC8598A/20200613114101.png

**Additional context**
A pen to reproduce the bug: https://codepen.io/peregrimm/pen/RwrRPKO?editors=1000

**Comment by mmmerl** [comment]
Thanks for finding (and fixing) this. I really appreciate the thorough bug report. I'll close now.

(Fixed by #29)
